name: Zazen Code
markdown: redcarpet
pygments: true
exclude: [README.md]

redcarpet:
  extensions: [with_toc_data]

asset:
  version: e

url: https://heristop.github.io

author: Alexandre Mog√®re
github: heristop
twitter: heristop
linkedin: heristop

description: Sharing practical tips and the latest trends in JavaScript, TypeScript and PHP
